core_default:
    path:     /
    defaults: { _controller: CoreBundle:Core:home }

core_homepage:
    path:     /public/homepage
    defaults: { _controller: CoreBundle:Core:home }
    
core_newcontent:
    path: /public/nouveautes
    defaults:
        _controller: CoreBundle:Core:newContent
        
core_additionnal_informations:
    path: /public/infos
    defaults:
        _controller: CoreBundle:Core:accessInfos
        
core_catalogue:
    path: /logged/catalogue
    defaults:
        _controller: CoreBundle:Core:accessCatalogue

core_event:
    path: /public/events
    defaults:
        _controller: CoreBundle:Event:displaysEvent
        
core_reservation:
    path: /gestion/reservations
    defaults:
        _controller: CoreBundle:Core:manageReservation

core_reserver_a_media:
    path: /logged/catalogue/reserve/{media_id}
    defaults:
        _controller: CoreBundle:Core:reserveMedia
        media_id: -1
        
core_user_res_and_load:
    path: /logged/MesReservationsEtEmprunts
    defaults:
        _controller: CoreBundle:Core:getUserMedia

core_gestion_valid_loan:
    path: /gestion/reservations/valid_loan/{res_id}
    defaults:
        _controller: CoreBundle:Core:validLoan
        res_id: -1
        
core_gestion_cancel_reservation:
    path: /gestion/reservations/cancel/{res_id}
    defaults:
        _controller: CoreBundle:Core:cancelReservation
        res_id: -1

core_gestion_valid_return:
    path: /gestion/reservations/return/{loan_id}
    defaults:
        _controller: CoreBundle:Core:validReturn
        loan_id: -1
        
    
core_user_cancel_reservation:
    path: /logged/reservations/cancel/{res_id}
    defaults:
        _controller: CoreBundle:Core:cancelReservationAsUser
        res_id: -1        


login:
    path: /login
    defaults:
        _controller: CoreBundle:User:login

login_check:
    path: /login_check
    
logout:
    path: /logout