<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Validator\Constraints\Date;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository {

    public function getNewContent() {
       $limitDate = new \DateTime();
       $limitDate->        
               setDate(2016, 10, 1);
      
     
        $qb = $this->createQueryBuilder('m')
                   ->where('m.date > :date')
                   ->setParameter('date', $limitDate)
        ;
        return $qb->getQuery()->getResult();
    }

}
